### ISSUE TITLE
issue when building bind

### ISSUE THREAD

**Issue by PeterMosmans** [goreliu/my-MSYS2-Packages#1]
Hi @goreliu , thanks for sharing your collection of packages.
When trying to build the latest version of bind using your PKGCONFIG on Windows (msys2/mingw64), I get the following error:

```
checking if unistd.h or sys/types.h defines fd_set... no
configure: error: need either working unistd.h or sys/select.h
```

Question: did you patch any other files, or do you use non-standard settings in your `makepkg.conf` ?

Thanks in advance,

Peter

**Comment by goreliu** [comment]
I built bind-9.10.4-P2 in MSYS2 Shell successfully.

[packages.txt](https://github.com/goreliu/my-MSYS2-Packages/files/472062/packages.txt)

[makepkg.log.gz](https://github.com/goreliu/my-MSYS2-Packages/files/472088/makepkg.log.gz)

**Comment by PeterMosmans** [comment]
Ah - that explains. I'm using the mingw64 shell of msys2:

```
$uname -s
MINGW64_NT-10.0
```

And it doesn't work for MINGW64. Thanks for the logs though.
